Velero
CentraleSupelec/kubic pull request #18
Opened 2023-05-09 08:28 UTC by ElieCaratge

2023-05-09 08:32 UTC, Quentique commented
Les fichiers dans le dossier `scaleway` devrait être un lien symbolique vers le fichier dans le dossier `common`, et on devrait trouver le même lien dans le dossier `ovh`.

2023-05-09 09:04 UTC, Quentique commented on common/velero-values.yml
> +  - name: velero-plugin-for-aws
```suggestion
  - name: velero-plugin
```

2023-05-09 09:04 UTC, Quentique commented on common/velero-values.yml
> +      - mountPath: /target
pourqoui /target ?

2023-05-09 09:05 UTC, Quentique commented on common/velero-values.yml
> +      region: sbg
Il faut 
```suggestion
      region: ${velero_s3_bucket_region}
```

2023-05-09 09:08 UTC, Quentique requested changes
Hop là

2023-05-09 09:08 UTC, Quentique commented on common/velero-values.yml
> +      region: "${velero_s3_bucket_region}"
Pourquoi des " ici ?

2023-05-09 09:08 UTC, Quentique commented on common/velero-values.yml
> +      # TODO: Compléter ceci
TODO ?

2023-05-09 09:08 UTC, Quentique commented on common/velero.tf
> +
Il faudrait rajouter une version ici et variabiliser

2023-05-09 09:08 UTC, Quentique commented on scaleway/velero-values.yml
> +  - name: velero-plugin-for-aws
```suggestion
  - name: velero-plugin
```

2023-05-09 09:08 UTC, Quentique commented on scaleway/velero-values.yml
> +      - mountPath: /target
/target ?

2023-05-10 13:39 UTC, ElieCaratge commented on scaleway/velero-values.yml
> +      - mountPath: /target
On va garder comme ca à priori, ca ne fonctionne pas sinon

2023-05-10 13:41 UTC, merged